from django.urls import path
from .views import (
    InitialRegistrationView, UserDetailsRegistrationView, OTPVerificationView,
    LanguagePreferenceView, UserTypeSelectionView, VehicleOwnerRegistrationView,
    IndustrialOwnerRegistrationView, LoginView, RegisterView, ResendOTPView,
    VerifyEmailView, UserProfileView, VehicleOwnerListView, VehicleOwnerDetailView,
    VehicleOwnerUpdateView, IndustrialOwnerUpdateView, ApproveVehicleOwnerView,
    VehicleDocumentListView, IndustrialDocumentListView, DocumentApprovalView,
    VehicleDocumentUploadView, IndustrialDocumentUploadView, IndustrialOwnerCreatePostView,
    VehicleOwnerPostListView, PostDeleteView, PostAcceptView, DeliveryScheduleView,
    PostCancelAcceptView, DeliveryStatusListView, UpdateDeliveryStatusView,
    AddVehicleView, VehicleListView
)

urlpatterns = [
    path('register/initial/', InitialRegistrationView.as_view(), name='initial-registration'),
    path('register/user-details/', UserDetailsRegistrationView.as_view(), name='user-details'),
    path('register/verify-otp/', OTPVerificationView.as_view(), name='verify-otp'),
    path('register/language/', LanguagePreferenceView.as_view(), name='language-preference'),
    path('register/user-type/', UserTypeSelectionView.as_view(), name='user-type-selection'),
    path('register/vehicle-owner/', VehicleOwnerRegistrationView.as_view(), name='vehicle-owner-registration'),
    path('register/industrial-owner/', IndustrialOwnerRegistrationView.as_view(), name='industrial-owner-registration'),
    path('vehicle-owner/add-vehicle/', AddVehicleView.as_view(), name='add-vehicle'),
    path('vehicle-owner/vehicles/', VehicleListView.as_view(), name='vehicle-list'),
    path('login/', LoginView.as_view(), name='login'),
    path('resend-otp/', ResendOTPView.as_view(), name='resend-otp'),
    path('verify-email/', VerifyEmailView.as_view(), name='verify-email'),
    path('profile/', UserProfileView.as_view(), name='user-profile'),
    path('vehicle-owners/', VehicleOwnerListView.as_view(), name='vehicle-owner-list'),
    path('vehicle-owners/<uuid:user_id>/', VehicleOwnerDetailView.as_view(), name='vehicle-owner-detail'),
    path('vehicle-owners/update/<int:vehicle_id>/', VehicleOwnerUpdateView.as_view(), name='vehicle-owner-update'),
    path('industrial-owners/update/', IndustrialOwnerUpdateView.as_view(), name='industrial_owner_update'),
    path('vehicle-owners/approve/<int:vehicle_id>/', ApproveVehicleOwnerView.as_view(), name='approve-vehicle-owner'),
    path('documents/vehicle/', VehicleDocumentListView.as_view(), name='vehicle-document-list'),
    path('documents/industrial/', IndustrialDocumentListView.as_view(), name='industrial-document-list'),
    path('documents/approve/<str:doc_type>/<int:doc_id>/', DocumentApprovalView.as_view(), name='document-approve'),
    path('documents/vehicle/upload/', VehicleDocumentUploadView.as_view(), name='vehicle-document-upload'),
    path('documents/industrial/upload/', IndustrialDocumentUploadView.as_view(), name='industrial-document-upload'),
    path('post_create/', IndustrialOwnerCreatePostView.as_view(), name='industrial_owner_create_post'),
    path('posts/', VehicleOwnerPostListView.as_view(), name='post_list'),
    path('posts/<str:post_id>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('posts/<str:post_id>/accept/', PostAcceptView.as_view(), name='post_accept'),
    path('posts/<str:post_id>/schedule/', DeliveryScheduleView.as_view(), name='delivery_schedule'),
    path('posts/<str:post_id>/cancel/', PostCancelAcceptView.as_view(), name='post_cancel'),
    path('posts/<str:post_id>/status/', DeliveryStatusListView.as_view(), name='delivery_status_list'),
    path('posts/<str:post_id>/update_status/', UpdateDeliveryStatusView.as_view(), name='update_delivery_status'),
]