# Generated by Django 5.2 on 2025-05-07 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="company_address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="company_reg_no",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="doc_is_approved",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="fleet_size",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="has_submitted_industrial_docs",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="has_submitted_vehicle_docs",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_industrial_owner",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_vehicle_owner",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="services_offered",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="vehicle_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="vehicle_no",
        ),
        migrations.AlterField(
            model_name="vehicleownerdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("vehicle_registration", "Vehicle Registration"),
                    ("identity_proof", "Identity Proof"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="IndustrialOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("company_address", models.TextField()),
                ("company_reg_no", models.CharField(max_length=30, unique=True)),
                ("designation", models.CharField(max_length=30)),
                ("has_submitted_industrial_docs", models.BooleanField(default=False)),
                ("doc_is_approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industrial_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_name", models.CharField(max_length=100)),
                ("vehicle_no", models.CharField(max_length=30, unique=True)),
                ("vehicle_model", models.CharField(max_length=100)),
                (
                    "vehicle_image",
                    models.ImageField(upload_to="vehicle_images/%Y/%m/%d/"),
                ),
                ("services_offered", models.TextField()),
                (
                    "driving_license_photo",
                    models.ImageField(
                        upload_to="vehicle_owner_docs/driving_license/%Y/%m/%d/"
                    ),
                ),
                (
                    "aadhar_photo",
                    models.ImageField(upload_to="vehicle_owner_docs/aadhar/%Y/%m/%d/"),
                ),
                (
                    "rc_document",
                    models.ImageField(upload_to="vehicle_owner_docs/rc/%Y/%m/%d/"),
                ),
                (
                    "insurance_document",
                    models.ImageField(
                        upload_to="vehicle_owner_docs/insurance/%Y/%m/%d/"
                    ),
                ),
                (
                    "kyc_document",
                    models.ImageField(upload_to="vehicle_owner_docs/kyc/%Y/%m/%d/"),
                ),
                ("insurance_number", models.CharField(max_length=50)),
                ("insurance_expiry_date", models.DateField()),
                ("rc_number", models.CharField(max_length=50)),
                ("rc_expiry_date", models.DateField()),
                ("kyc_number", models.CharField(max_length=50)),
                ("kyc_expiry_date", models.DateField()),
                ("has_submitted_vehicle_docs", models.BooleanField(default=False)),
                ("doc_is_approved", models.BooleanField(default=False)),
                ("number_of_vehicles_expired", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
