# Generated by Django 5.1.7 on 2025-03-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="contact_no",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
