# Generated by Django 5.1.7 on 2025-03-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_contact_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_industrial_owner",
            field=models.BooleanField(default=False),
        ),
    ]
