# Generated by Django 5.2 on 2025-05-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_customuser_company_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
