# Generated by Django 5.1.7 on 2025-03-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_is_industrial_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_approved",
            new_name="doc_is_approved",
        ),
    ]
