# Generated by Django 5.1.6 on 2025-03-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_fleet_size_customuser_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('industrial_owner', 'Industrial Owner'), ('vehicle_owner', 'Vehicle Owner'), ('admin', 'Admin')], max_length=20),
        ),
    ]
