# Generated by Django 5.1.7 on 2025-03-22 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_is_approved_customuser_doc_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_submitted_industrial_docs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="has_submitted_vehicle_docs",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="IndustrialOwnerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("industrial_certificate", "Industrial Certificate"),
                            ("industrial_license", "Industrial License"),
                            ("identity_proof", "Identity Proof"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_image",
                    models.ImageField(upload_to="industrial_documents/%Y/%m/%d/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industrial_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "document_type")},
            },
        ),
        migrations.CreateModel(
            name="VehicleOwnerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("vehicle_registration", "Vehicle Registration"),
                            ("driving_license", "Driving License"),
                            ("identity_proof", "Identity Proof"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_image",
                    models.ImageField(upload_to="vehicle_documents/%Y/%m/%d/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "document_type")},
            },
        ),
    ]
