# Generated by Django 5.2 on 2025-05-07 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_auto_20250507_1112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleowner",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
