# Generated by Django 5.1.7 on 2025-04-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_post_accepted_by_post_status_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="delivery_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
